name: Build and Deploy Docker Image

on:
  push:
    branches: [main]  
  pull_request:
    branches: [main]

env:
  DOCKERHUB_REPO: reecetec/juicebox

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest pytest-cov
      
      - name: Run tests
        run: |
          pytest tests/ --cov=src/sportsflow --cov-report=xml
        continue-on-error: false  

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=sha,prefix=sportsflow-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
      
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}

# Update airflow helm chart to use the new image tag
# update-manifests:
#   needs: build-and-push
#   runs-on: ubuntu-latest
#   if: github.ref == 'refs/heads/main'
#   
#   steps:
#     - name: Checkout GitOps repo
#       uses: actions/checkout@v4
#       with:
#         repository: juicebox-platform/gitops
#         token: ${{ secrets.GITOPS_TOKEN }}
#         path: k8s-manifests
#     
#     - name: Update image tag in Helm values
#       run: |
#         cd k8s-manifests
#         
#         # This now matches the tag format from the build job
#         IMAGE_TAG="sportsflow-${GITHUB_SHA::7}"
#         
#         # Update the image tag in your Helm values file
#         # This assumes you are using sed. You might need to adjust for your file structure.
#         sed -i "s|tag: .*|tag: ${IMAGE_TAG}|g" path/to/your/values.yaml
#         
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git add .
#         git commit -m "Update image to ${{ env.DOCKER_IMAGE }}:${IMAGE_TAG}" || exit 0
#         git push

